version: '3'

networks:
    lemp:

services:
    nginx:
        image: nginx:stable-alpine
        container_name: lemp_nginx
        ports:
            - "8080:80"
        volumes:
            - ./src:/src
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - lemp

    mysql:
        image: mysql:latest
        container_name: lemp_mysql
        volumes:
            - ./db_data:/var/lib/mysql
        ports:
            - "33060:3306"
        depends_on:
            - nginx
        environment:
            - MYSQL_ROOT_PASSWORD=secret
        networks:
            - lemp

    php:
        image: php:7-fpm-alpine
        container_name: lemp_php
        volumes:
            - ./src:/src
        ports:
            - "9000:9000"
        networks:
            - lemp

volumes:
    src:
